# Generated by Django 5.0.2 on 2024-02-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('blog', '0003_blogpost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(to='authors.author'),
        ),
    ]
