# Generated by Django 5.0.2 on 2024-02-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
