# Generated by Django 5.0.2 on 2024-02-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_image_filename_media_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image_filename',
        ),
    ]
